### ISSUE TITLE
Metadata with spaces not allowed

### ISSUE THREAD

**Issue by kjk** [kurin/blazer#13]
I'm using the library in a simple file backup to backblaze program. 

The backblaze path is sha1 of the content so I'm using metadata to store the original file path, i.e. something like:
```go
dst := obj.NewWriter(ctx)
info := make(map[string]string)
info["path"] = filePath
attrs := b2.Attrs{
	Info: info,
}
dst = dst.WithAttrs(&attrs)
...
```

When path has spaces in it (as it happens sometimes), I get the error:
```
2017/06/06 22:19:13 error writing files/0f/82/0f822a8bc2600860b6066bca0e0df11349ecb5ff.pdf: b2_upload_file: 400: Bad character in percent-encoded string: 32 (0x20)
BackblazeUploadFileWithMetadta() failed with b2_upload_file: 400: Bad character in percent-encoded string: 32 (0x20)
```

I assume that value (and key?) of metadata must be url-escaped?

Also, the debug log message shouldn't be there (I don't have `B2_LOG_LEVEL` set).

**Comment by kurin** [comment]
Oh, yeah, I've been meaning to fix this.

**Comment by kurin** [comment]
The rules for string encoding are https://www.backblaze.com/b2/docs/string_encoding.html

I'll try to address this tomorrow.

**Comment by kurin** [comment]
It looks like url.PathEscape is really all I need.

**Comment by kurin** [comment]
Try this and see how it works for you.

**Comment by kjk** [comment]
Almost there. Handles spaces but still fails for e.g. `BackblazeUploadFileWithMetadta(/Volumes/Store/books/_djvu/Advanced Compiler Design & Implementation.djvu) failed with b2_upload_file: 400: Bad character in percent-encoded string: 38 (0x26)`

**Comment by kurin** [comment]
Ah, even url.QueryEscape wouldn't work, because it would erroneously escape /.

Try again with the latest commit.

**Comment by kjk** [comment]
It now uploaded the failing file, thanks!
