### ISSUE TITLE
An easy way to check if file exists in backblaze

### ISSUE THREAD

**Issue by kjk** [kurin/blazer#14]
I can't figure out how to (easily) find out if file already exists.

I tried:
```go
func BackblazeExists(b2Path string) (bool, error) {
	ctx := context.Background()
	bucket, err := getBucket(ctx)
	if err != nil {
		return false, err
	}

	obj := bucket.Object(b2Path)
	_, err = obj.Attrs(ctx)
	if err == nil {
		return true, nil
	}
	if b2.IsNotExist(err) {
		return false, nil
	}
	return false, err
}
```
But the error from obj.Attrs() is `b2_download_file_by_name: 404: bucket kjkpub does not have file:` and doesn't match `b2.IsNotExist()`.

I can think of few (unsatisfactory) work-arounds, given the current api:
* I could assume that every error from obj.Attrs() means "doesn't exit", but that's not entirely correct.
* I could match the error text for "does not have file" but that seems hacky.
* I could use ListCurrentObjects().

Possible solutions in the library:
* expose `Bucket.getObject` as `Bucket.getObject` so that I don't have to use `Object.Attrs()`
* have `Object.Attrs()` return an error with `notFoundErr = true` for the case of "object doesn't exist"

Also, example for that in readme would be good.

**Comment by kurin** [comment]
There is AFAICT no way to get this information from the writer, which is a shame.

Attrs() should IsNotExist correctly.
