### ISSUE TITLE
Inefficient listing of files (including metadata)

### ISSUE THREAD

**Issue by kjk** [kurin/blazer#16]
I need a cheap way to list existing items including the basic info (size etc.).

I did the obvious thing:
* use `Bucket.ListCurrentObjects`
* for each object received, call `Object.Attrs`

Currently in that case `Object.Attrs` involves another HTTP call, which is slow and costly.

It looks like the http api used by `Bucket.ListCurrentObjects` returns the necessary data so it seems possible to construct `Object.Attrs` out of that and cache it.

I looks I could use the lower-level base API, but I'm told not to :)

**Comment by kurin** [comment]
Objects are immutable (I think?  I fervently hope) so caching the attrs certainly seems reasonable.

**Comment by kurin** [comment]
Try now with cached attrs.

**Comment by kjk** [comment]
Yep, much faster, thanks!
