### ISSUE TITLE
Request for full usage example

### ISSUE THREAD

**Issue by xanderseren** [kurin/blazer#18]
I'm trying to implement file uploads using this library, but can't quite get wrap my head around the correct flow of credentials/configuration to uploading the file itself. If someone could add an example usage in the docs a la https://github.com/mitchellh/goamz that would be super helpful.

**Comment by kurin** [comment]
I've added an example program here: https://github.com/kurin/blazer/blob/master/examples/simple/simple.go

Is this helpful?

**Comment by xanderseren** [comment]
This is great, thank you!!
