### ISSUE TITLE
Maybe use hex_digits_at_end now that B2 supports it

### ISSUE THREAD

**Issue by kurin** [kurin/blazer#24]
According to https://www.backblaze.com/b2/docs/uploading.html, we're no longer obligated to send the SHA1 hash in the header.  This could save memory.  Explore this.

**Comment by kurin** [comment]
I'm actually not convinced it will, especially with multiple upload streams.  If we're going to be uploading 5 100MB chunks concurrently (say) from an input stream, we still have to read all the way through chunks 1-4 and stash those somewhere before we can start on 5.

**Comment by someone1** [comment]
If you introduced a different interface to upload files I think you could optimize memory usage by doing something similar to what the s3manager does for the AWS Go SDK, something like an UploadFile function that takes in an io.Reader and tests it for additional capabilities similar to the AWS package?

Reference:
https://github.com/aws/aws-sdk-go/blob/master/service/s3/s3manager/upload.go#L510

**Comment by kurin** [comment]
A different interface is particularly what I want to avoid.  More knobs on the b2.Writer struct are fine though.

I think you're right that this and #4 are complementary.  The problem with #4 is that I don't want to (unconditionally) issue multiple reads of files even if they're "on disk" because they might actually not be.  But if I can append the digest, then I only have to read once and that issue becomes moot.

So then, if the Writer implements ReadFrom, it can test whether the Reader is actually a ReadSeeker and, if so, upload _in situ_ with only one pass per chunk.  (It can also get the file length by seeking to the end and back, and choose upfront whether it's a regular or large file upload, which I like.)

**Comment by someone1** [comment]
SGTM! I think the AWS SDK also does similar size detection: https://github.com/aws/aws-sdk-go/blob/master/service/s3/s3manager/upload.go#L482 - it also falls back to a small upload if the file size is below the specified chunk size.

I like that you're sticking with the standard Go interfaces 😄

**Comment by kurin** [comment]
Take a look at head if you have a use for this; I've confirmed that it really cuts down on memory when copying directly from an os.File.
