### ISSUE TITLE
Blazer is returning transient errors to the client.

### ISSUE THREAD

**Issue by kurin** [kurin/blazer#34]
https://github.com/restic/restic/issues/1351#issuecomment-336624736

**Comment by armhold** [comment]
I think you left off some Sprintf() arg in https://github.com/kurin/blazer/blob/master/base/base.go#L136 and https://github.com/kurin/blazer/blob/master/base/base.go#L142.

BTW, my guess is that some Backblaze front end (Apache, or similar) is producing the 503s, rather than the part of their stack that would normally write the JSON error.

I won't have time until late tomorrow, but if I wanted to capture the response for you to debug, what's the best way to do that? Haven't had a chance to explore the B2 logging infra yet...

**Comment by kurin** [comment]
Er, yes.  I'll run go vet in travis to catch those.

I think you're right, and I'm about 80% sure the errors were coming from https://github.com/kurin/blazer/blob/master/base/base.go#L140.  For some reason blazer's logger (which uses the stdlib logger) doesn't print anywhere that I could find under restic (I didn't look super hard).  I would honestly just fmt.Printf(string(data)) on line 141 and see what happens.

**Comment by kurin** [comment]
Println.  Whichever.

**Comment by tylerchr** [comment]
I ran into this issue via restic as well, and also traced the cause back to `mkErr`. My logging in there reports that the response was as simple as this:

(This was from a request to https://api001.backblazeb2.com/b2api/v1/b2_get_upload_url).

```
HTTP/1.1 503 Service Unavailable
Server: Apache-Coyote/1.1
Date: Mon, 16 Oct 2017 07:40:14 GMT
```

This essentially matches the behavior recorded in the debug log in https://github.com/restic/restic/issues/1351#issuecomment-336704565, which had this for the same request:

```
HTTP/1.1 503 Service Unavailable
Connection: close
Transfer-Encoding: chunked
Date: Sat, 14 Oct 2017 11:30:14 GMT
Server: Apache-Coyote/1.1
```

Notably, there is neither a `Content-Length` header nor a body.

The Backblaze [Integration Checklist](https://www.backblaze.com/b2/docs/integration_checklist.html) does make mention of the fact that 503s from certain API calls should be retried according to the `Retry-After` header if present (obviously not present here) or exponential backoff if not. It doesn't appear to make any promises about the response body.

> 503 errors from any API except b2_upload_file or b2_upload_part. (Handling a 5xx error on an upload API is described in the Uploading Files section above.) When this error occurs, it may include a "Retry-After" header where the value is the number of seconds a developer should wait before re-issuing the command. If the header is not present, the developer should retry using an expotential backoff starting with 1 second. These status codes may be returned from any B2 API.

**Comment by kurin** [comment]
Okay, so that's why ReadAll is getting data and it's dying in json.Unmarshal.

The code currently in master should handle this gracefully; I'll write tests simulating the empty 503s so I can close this bug.

Thanks.

**Comment by armhold** [comment]
Agree that's where & why it's failing, but hard to blame Blazer here, since the Backblaze documentation [seems to promise](https://www.backblaze.com/b2/docs/calling.html#error_handling) a JSON error response for 503s:

```
Any code other than 200 is an error, and the response will contain a 
JSON error structure indicating what went wrong
```
Like I said above, my guess is that their stack normally does provide this, but if some service is down maybe Apache is just giving the minimal 503 response without the JSON. Either way, I think it's best to program defensively here.

**Comment by tylerchr** [comment]
Ah great observation, I missed that. In that case, agree that you're exactly right.

For curiosity's sake, I dropped Backblaze a note—we'll see what they have to say for themselves. :)

**Comment by kurin** [comment]
Backblaze has a curiously removed attitude towards B2 dev projects, but I'm curious to see their response if they have one.

I think what it is is that the _file upload_ APIs are guaranteed a JSON response, but not other APIs.  The HTTP header that requests an elevated failure rate only returns 503s from those APIs, so this isn't often seen in integration tests (it's called "fail_some_uploads").

**Comment by kurin** [comment]
I'm able to reproduce this now (albeit stochastically):

Before 

    2017/10/19 23:54:53 >> b2_get_upload_url uri: https://api001.backblazeb2.com/b2api/v1/b2_get_upload_url headers: {X-Bz-Test-Mode: fail_some_uploads,expire_some_account_authorization_tokens;User-Agent: integration-test b2-test blazer/0.2.1;X-Blazer-Request-Id: 4} args: ({"bucketId":"420da65004f7357753f3081d"})
    2017/10/19 23:54:53 << b2_get_upload_url (4) 503 Service Unavailable {} ()
    2017/10/19 23:54:53 error writing Teeny Tiny: unexpected end of JSON input

After

    2017/10/20 00:10:39 >> b2_get_upload_url uri: https://api001.backblazeb2.com/b2api/v1/b2_get_upload_url headers: {X-Bz-Test-Mode: fail_some_uploads,expire_some_account_authorization_tokens;User-Agent: integration-test b2-test blazer/0.2.1;X-Blazer-Request-Id: 4} args: ({"bucketId":"b2fd165014e7357753f3081d"})
    2017/10/20 00:10:39 << b2_get_upload_url (4) 503 Service Unavailable {} ()
    2017/10/20 00:10:40 >> b2_get_upload_url uri: https://api001.backblazeb2.com/b2api/v1/b2_get_upload_url headers: {User-Agent: integration-test b2-test blazer/0.2.1;X-Blazer-Request-Id: 5;X-Bz-Test-Mode: fail_some_uploads,expire_some_account_authorization_tokens} args: ({"bucketId":"b2fd165014e7357753f3081d"})

**Comment by kurin** [comment]
So I'm fairly happy that this specific issue is resolved.
