### ISSUE TITLE
Blazer should test and handle all tcp/http/tls connection issues.

### ISSUE THREAD

**Issue by kurin** [kurin/blazer#35]
Found in https://github.com/restic/restic/issues/1351

**Comment by kurin** [comment]
A lot of this is caught (I think) here https://github.com/kurin/blazer/blob/master/base/base.go#L388 but eyeballing it I didn't build in the same protection here https://github.com/kurin/blazer/blob/master/base/base.go#L1076

**Comment by kurin** [comment]
This fragile channel nonsense could stand to be stuffed into a single function.

**Comment by kurin** [comment]
In fact none of it needs to exist now that the http package supports contexts.

**Comment by someone1** [comment]
maybe i missed it but did you actually call WithContext anywhere when making the request? Doesn't appear so?

**Comment by kurin** [comment]
Haha, whoops, good catch.

I thought I had a test for this exact thing; I guess I need one.
