### ISSUE TITLE
Support download tokens with b2ContentDisposition

### ISSUE THREAD

**Issue by kennylevinsen** [kurin/blazer#52]
Download URL's take two query parameters, both optional: Authorization and b2ContentDisposition (see: https://www.backblaze.com/b2/docs/b2_download_file_by_name.html)

If an authorization token is used for download, the value of b2ContentDisposition must also have been specified byte-for-byte in the request to get_download_authorization when creating the token (see: https://www.backblaze.com/b2/docs/b2_get_download_authorization.html).

blazer does not have support for specifying b2ContentDisposition to get_download_authorization, and tokens generated by AuthToken can thus not be used with the b2ContentDisposition query parameter.

**Comment by kurin** [comment]
I think we did this in another bug?  I remember kicking around a couple ideas, and Object.AuthURL does this now.  I'm going to close this, but reopen and let me know if I'm confused and this is actually asking for a different thing.
