### ISSUE TITLE
Feature request: GetAuthorizedURL on Object

### ISSUE THREAD

**Issue by kennylevinsen** [kurin/blazer#53]
It feels awfully dirty to `fmt.Sprintf` direct embedded-authorization URLs.

Something like:
```go
func (*Object) GetAuthorizedURL(ctx context.Context, validity time.Duration) (*url.URL, error) {}
func (*Object) GetAuthorizedURLWithContentDisposition(ctx context.Context, validity time.Duration, contentDisposition string) (*url.URL, error) {}
```

... Would feel a lot cleaner than:

```go
token, err := bucket.AuthToken(ctx, name, validity)
if err != nil {
...
}

u, err := url.Parse(fmt.Sprintf("%s/file/%s/%s?Authorization=%s", bucket.BaseURL(), bucket.Name(), name, url.QueryEscape(token)))
if err != nil {
...
}

return u, nil
```

**Comment by kurin** [comment]
I wish I knew how often people just wanted to share one object vs wanting an auth token for a common prefix of many objects.

What about something like

```go
type Token string

func (t Token) URL(o *Object) (*url.URL, error)
```

so that getting auth tokens is still essentially a bucket operation, but has a convenience method for individual objects.

**Comment by kennylevinsen** [comment]
I can't really come up with a real use-case for issuing a token for a prefix of many objects, instead of just using a token per object, but that may of course just be because I am a bit too focused on the use-cases I have experienced myself.

That interface would seem slightly quirky. First of all, it's a bit repetitive:

```go
token, _ := bucket.AuthToken(ctx, objectName, validity)
obj := bucket.Object(objectName)
url, _ := token.URL(obj)
```

Second, it would blindly generate URL's for objects that the token is incapable of serving, making it a bit error-prone. In case of b2ContentDisposition, the token will be even more limited in use (which I unfortunately need...).

I personally like the idea of having automatic token issue on Object convenience methods better, as it is both more convenient and more robust. I won't cry myself to sleep if that doesn't happen, though. :)

**Comment by kurin** [comment]
I'm interested in avoiding API bloat, but I think you're right that your use case is probably fairly common, enough so to warrant these helpers.

I would like to avoid two different methods though.  I'm starting to worry that I'm overusing the [ThingOption](https://godoc.org/github.com/kurin/blazer/b2#ClientOption) pattern a little bit, but it could apply here.  Alternatively we could just leave that argument empty for no b2ContentDisposition argument.

**Comment by kurin** [comment]
B2 doesn't have any documentation that I've found specifying how _many_ auth tokens you're able to get.  (You also apparently can't revoke them once you have them.)  So I guess it could just generate a new token each time.

**Comment by kurin** [comment]
Take a look at that PR and see if it's something that would fit your use case.

It requests a new token for every call to AuthURL(), which I figure if people want to cache it they can probably do that themselves.

**Comment by kennylevinsen** [comment]
I haven't tested it, but that PR fits my use-case perfectly, and in the most convenient way it could be done, so I couldn't be happier!

I would have commented that you should add a few url.QueryEscape calls, but you beat me to it.
