### ISSUE TITLE
Slightly extend `base` interface for stateless programs

### ISSUE THREAD

**Issue by ppolewicz** [kurin/blazer#62]
The user of Blazer-powered program might be presented with a list of unfinished large file uploads in B2 and after some time (think a next request through the browser) might decide to pick one and cancel it permanently. The problem is, if I understood correctly, that blazer exposes an object, but does not expose the B2's identifier of the upload (`File.id` - it is being held in a private variable of the object). Therefore it is not possible to reliably identify the file chosen by the user to cancel after the object is freed from memory. We can't really keep it in memory, as we have no idea whether and when the user would choose to cancel it...

The `b2` public interface layer could hide internal cloud identifiers, however:
- this repository contains the only maintained golang implementation of B2 client as of today
- `b2` is a high-level interface, specifically designed to abstract away the Backblaze API details by providing familiar Go interface
- **BUT** Blazers `base` is a "very low-level interface on top of the B2 v1 API", which is **not intended to be used directly**

Exposure of this `File.id` identifier from the large file upload list function would require that:
- the `base` layer of Blazer to be modified (here the `b2` "officially" public interface would not change at all)
- (more importantly) a change in mindset of what the `base` package is for, to officially allow others to use `base` as a, uh, base for their software

Obviously, while the first part is trivial, the second one requires careful consideration.

This issue is currently affecting Blazer users today - if someone wants to implement a program in golang and that program needs the internal details such as `File.id`, they are **copying the source code of Blazer's `base` into their project**, modifying the visibility of a field and leaving it there without any updates Blazer team is doing, for years. Therefore in my opinion, exposure of a few fields and removal of _not intended to be used directly_ restriction would make the world a better place.

If my understanding is correct, such changes should not break the actual `b2` package, but if they did, matching changes would need to be done accordingly in both packages in the same PR, as well as in any unit tests, documentation etc, to follow the quality standard you have set in the project. I would take care of all that to the satisfaction of the maintainer of the repository, if the change is pre-approved in the discussion below.

Would it be ok for `base` to be allowed to be used by other developers?

Would it be ok to merge a PR which would to expose a currently private field (as discussed above) in the `base` package (while making sure that `b2` is not negatively affected)?

**Comment by kurin** [comment]
Hi Paweł, thanks for opening a ticket.  So that I'm clear, the scenario is that a modification to the contents of B2 could be made that is not identifiable in blazer?  I'm not against exposing `base.File.id` but I feel like this is something that could be handled better by e.g. relisting unfinished files.

I'd like to see a code snippit that benefits from this, if possible?  Thanks.

**Comment by ppolewicz** [comment]
listing unfinished files is not free: it's a "C" transaction, limited to 2500 free calls per day, so I'd rather avoid a double call

**Comment by ppolewicz** [comment]
If we consider a http server, it could serve something like this:
```
GET /listUnfinishedFiles?bucketId=abcdef
```
Which could return a list of objects, in json or something.

But then how should the request for cancelling a large fine upload look like?
```
POST /cancelLargeFileUpload
bucketId=abcdef&fileId=ac4ef79a16d38b4c2d80
```
Seems like a natural solution. Since B2 allows multiple large file uploads of the same filename to exist, providing a functionality of cancelling user-selected large file upload session would be very messy without the fileId.

**Comment by mzukowski-reef** [comment]
@kurin you asked for snippet that benefits from this change - here is WIP commit in `minio/minio` to switch from their fork (`minio/blazer`) to this repo - https://github.com/mzukowski-reef/minio/commit/c455ad3425408415797d89a1ecc1d949827b0e7e - you can see there changes required in `minio` code to support changes in code commited in PR #65 as well as how `kurin/blazer/base` is used in `minio` code
