### ISSUE TITLE
Get a file at a specific version (ID)

### ISSUE THREAD

**Issue by wavded** [kurin/blazer#64]
From what I can tell from reading the docs and looking at the issues is to get all versions of a file I need to use the ListHidden option. However, if I want to get a particular file at a specific version (using the direct fileID I believe), I don't see a way to do that. Can this be added or can I be corrected if I missed something?

**Comment by wavded** [comment]
I attempted to download a specific version using the the `ListHidden` option and an index (not terribly reliable of course) and looks like I found potential bug as well. Calling `iter.Object().NewReader(context)` when accessing an object that is a previous version of a file always gets me the latest version because NewReader appears to use the `downloadFileByName` from B2.

**Comment by kurin** [comment]
This sounds similar enough to #62 that they probably should be solved together as soon as I have some time, which should be this week or next.

**Comment by wavded** [comment]
Hey @kurin,  any plans still on this?
