### ISSUE TITLE
Question about the state of this library.

### ISSUE THREAD

**Issue by Elycin** [kurin/blazer#69]
Hello, 

I'm inquiring about the state of this library. I'm looking forward to using it as it seems like a viable alternative to go-backblaze but I see that it hasn't been maintained in 8 months other than one pull request.

Is this planned on still being actively maintained or are you looking for someone to pick up the project?

Regards,
Ely Haughie

**Comment by kurin** [comment]
Hi @Elycin,

I haven't really had free time to work on new features, but I do try to get to any breaking bugs within a day or so.  I would of course welcome any patches.
