### ISSUE TITLE
Operations on 0-byte-files fail with 416: out of content

### ISSUE THREAD

**Issue by aksdb** [kurin/blazer#71]
Any operation (even delete!) calls "ensure" which involes "downloadFileByName". If the file has a size of 0, b2 fails with "416: out of content". Therefore it is impossible to do anything (using blazer) on 0-byte files, currently.

(Although I'm not sure if this might be a bug on B2 side ... since requesting the range 0 to 0 of a 0-byte file ... doesn't exactly sound like an invalid request. It seems like they simply deny "range" when the file is empty.)

**Comment by kurin** [comment]
Yeah, this was a hack to get the file ID, which is a required field to pretty much every other API call, including b2_delete_file_version, and, it looks like, b2_get_file_info, still.

**Comment by kurin** [comment]
I think probably the best way around this is to look for 416 and resubmit without a Range header.  This will incur a latency hit.  Out of curiosity, how many zero-byte files do you have?

**Comment by aksdb** [comment]
According to the docs - and confirmed by a quick curl request - a `HEAD` request should do the job (without any range):

https://www.backblaze.com/b2/docs/b2_download_file_by_name.html

**Comment by aksdb** [comment]
Oh and: I don't have many 0 byte files. Actually I just stumbled upon this while running integration tests. It seems like a potential, hard to debug problem, though, should this hit production (like: deletion works in 99,999% of cases ... but sometimes a weird error is thrown) :D

**Comment by kurin** [comment]
I mean, when you say it like that it makes it sound so obvious.

**Comment by aksdb** [comment]
In hindsight solutions often seem obvious :smile: 
Thanks for fixing this so fast!
