### ISSUE TITLE
Supply optional bucketName parameter to listBuckets

### ISSUE THREAD

**Issue by gsauthof** [kurin/blazer#76]
Looking at the `listBuckets()` result traversals in `Bucket()` and `NewBucket()`, e.g.

https://github.com/kurin/blazer/blob/ed62b35677f8ba19860aaacef0ef70a3c695c35f/b2/b2.go#L284-L298

there is a (small) optimization opportunity to supply the bucket name to the optional `bucketName` parameter of [`b2_list_buckets`][1]. Then the returned bucket list would be at most one element long, thus limiting the number of iterations in those functions to one.

[1]: https://www.backblaze.com/b2/docs/b2_list_buckets.html

**Comment by kurin** [comment]
Good point.  Thanks!
