### ISSUE TITLE
Please add the option to set a custom Transport (http.RoundTripper)

### ISSUE THREAD

**Issue by fd0** [kurin/blazer#9]
Hi,

for [restic](https://github.com/restic/restic) we have a custom `http.RoundTripper` for multiple backends so that we can configure settings like the number of idle HTTP/TLS connections per host. Can you maybe add an option to use a custom transport for blazer? The minio-go s3 library has a method for it: https://godoc.org/github.com/minio/minio-go#Client.SetCustomTransport, the swift library by ncw has a field in the Connection struct: https://godoc.org/github.com/ncw/swift#Connection

I don't have any particular preference for either, I'd just like to use our `http.RoundTripper` :)

If you're interested in a PR proposing an API, please let me know, I'd work on that.

Thanks!

**Comment by kurin** [comment]
I agree with your suggestion in #10 that having a RoundTripper per Client is better than a package-level variable.

I think what I want to do is modify base.AuthorizeAccount to take optional parameters to set this (and maybe other) behavior.  E.g. from

    func AuthorizeAccount(ctx context.Context, account, key string) (*B2, error)

to

    func AuthorizeAccount(ctx context.Context, account, key string, opts ...Options) (*B2, error)

akin to grpc.DialOptions.  These would then propagate to everything set downstream, and would be exposed in b2 somehow as well.  What do you think?

**Comment by fd0** [comment]
Sounds good to me! A per-client configuration method is much better. Do you have a timeline for that?

**Comment by kurin** [comment]
I can probably get something out today.

**Comment by fd0** [comment]
That'd be awesome! I'm about to merge the b2 backend for restic, see https://github.com/restic/restic/pull/978
